theme: jekyll-theme-merlot
# Site
title:  blog
subtitle: ''
description: Just Do It,But Not Just Do It.
keywords:
author: Yang
language: zh-CN
timezone: ''
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 'git'
  repo: git@github.com:duizhanghenmang/duizhanghenmang.github.io.git
  branch: master
